In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import time
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

In [0]:
df = pd.read_csv('mean-value-c2.csv')
dataset = df.values
X = dataset[:,0:16].astype(float)
y = dataset[:,16:19]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33, test_size=0.2, stratify=y)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [0]:
model =  tf.keras.models.load_model('model30.h5')

In [101]:
pred=model.predict_classes(X_test)
y2 = y_test.argmax(axis=1)
cm=confusion_matrix(y2, pred)

print(cm)

[[13  0  0]
 [ 0 12  1]
 [ 0  1 12]]


In [0]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    import itertools
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('Label Asli')
    plt.xlabel('Label Prediksi')
    plt.tight_layout()

In [103]:
# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cm, classes=['PF1', 'PF2', 'BOHEA'],
                      

SyntaxError: ignored